language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- DB_USERNAME=nedsoft DB_PASSWORD=password DBNAME=ned_politico
before_script:
- psql -c 'create database ned_politico;' -U postgres
- psql -c "CREATE USER nedsoft WITH PASSWORD 'password';" -U postgres
script: npm test
after_success: npm run coveralls

