const users = `CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  otherName VARCHAR(50) DEFAULT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  role VARCHAR(20) DEFAULT('voter'),
  isAdmin BOOLEAN DEFAULT false,
  password VARCHAR(100) NOT NULL,
  phone VARCHAR(15) DEFAULT NULL,
  passportUrl VARCHAR(200) DEFAULT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const parties = `CREATE TABLE IF NOT EXISTS parties(
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  hqAddress VARCHAR(100),
  logourl VARCHAR(200),
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const offices = `CREATE TABLE IF NOT EXISTS offices(
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(100),
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const candidates = `CREATE TABLE IF NOT EXISTS candidates(
  id SERIAL PRIMARY KEY,
  office INTEGER REFERENCES offices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  party INTEGER REFERENCES parties(id) ON DELETE CASCADE ON UPDATE CASCADE,
  candidate INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const votes = `CREATE TABLE IF NOT EXISTS votes(
  id SERIAL PRIMARY KEY,
  office INTEGER REFERENCES offices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  candidate INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdBy INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const petitions = `CREATE TABLE IF NOT EXISTS petitions(
  id SERIAL PRIMARY KEY,
  office INTEGER REFERENCES offices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdBy INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  body TEXT NOT NULL,
  evidence VARCHAR (200) [],
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

const restults = `CREATE TABLE IF NOT EXISTS results(
  id SERIAL PRIMARY KEY,
  office INTEGER REFERENCES offices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  candidate INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  result INTEGER DEFAULT 0
)`;

export default {
  users,
  parties,
  offices,
  candidates,
  votes,
  petitions,
  restults,
};
